[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#7D56F4"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2226"
textColor = "#FAFAFA"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[logger]
level = "info"